#!/bin/bash
set -e

# generate-docs-index.sh
# Generates a root index.html listing all available API documentation versions.

DOCS_ROOT=$1

if [ -z "$DOCS_ROOT" ]; then
    echo "Usage: $0 <docs_root_directory>"
    exit 1
fi

INDEX_FILE="$DOCS_ROOT/index.html"
VERSIONS_DIR="$DOCS_ROOT/versions"

echo "Generating index.html in $DOCS_ROOT..."

# Start HTML content
cat > "$INDEX_FILE" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpenTrusty API Documentation</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
        h1 { border-bottom: 2px solid #eaeaea; padding-bottom: 10px; }
        .version-list { list-style: none; padding: 0; }
        .version-item { margin: 10px 0; padding: 15px; background: #f6f8fa; border-radius: 6px; display: flex; justify-content: space-between; align-items: center; }
        .version-item:hover { background: #eef1f4; }
        .version-link { text-decoration: none; color: #0366d6; font-weight: bold; font-size: 1.1em; }
        .latest-badge { background: #28a745; color: white; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; margin-left: 10px; }
    </style>
</head>
<body>
    <h1>OpenTrusty API Documentation</h1>
    <p>Select a version below to view the interactive API reference.</p>
    <ul class="version-list">
EOF

    # Find versions, sort them (reverse version sort), and add to list
    # Use sort -Vr for version sort reverse
    VERSIONS=$(ls "$VERSIONS_DIR" | sort -Vr)
    
    FIRST=true
    for VERSION in $VERSIONS; do
        LINK="versions/$VERSION/index.html"
        
        BADGE=""
        # Only assign Latest badge to GA releases (no alpha/beta/rc)
        if [ "$FIRST" = true ] && [[ ! "$VERSION" =~ -(alpha|beta|rc)\. ]]; then
            BADGE="<span class='latest-badge'>Latest</span>"
            FIRST=false
        fi

        echo "        <li class=\"version-item\">" >> "$INDEX_FILE"
        echo "            <a class=\"version-link\" href=\"$LINK\">$VERSION</a>$BADGE" >> "$INDEX_FILE"
        echo "        </li>" >> "$INDEX_FILE"
    done
else
    echo "<p>No versions available.</p>" >> "$INDEX_FILE"
fi

# Close HTML
cat >> "$INDEX_FILE" <<EOF
    </ul>
    <footer style="margin-top: 50px; color: #666; font-size: 0.9em;">
        <p>Generated by OpenTrusty CI/CD</p>
    </footer>
</body>
</html>
EOF

echo "✅ Generated $INDEX_FILE"
