#!/bin/bash
# generate-test-report.sh
# Generates a Markdown test report from Go test JSON output
#
# Usage: ./scripts/generate-test-report.sh [REPORT_DIR]
#
# This script parses Go test JSON output and generates:
# - test-report.md: Human-readable Markdown report
# - test-summary.json: Machine-readable summary for docs generation

set -e

REPORT_DIR="${1:-./build_docs/test-reports}"
OUTPUT_FILE="${REPORT_DIR}/test-report.md"
SUMMARY_FILE="${REPORT_DIR}/test-summary.json"

echo "📊 Generating test report from ${REPORT_DIR}..."

# Initialize counters
UNIT_PASS=0
UNIT_FAIL=0
UNIT_SKIP=0
SYSTEM_PASS=0
SYSTEM_FAIL=0
SYSTEM_SKIP=0

# Parse unit test results
if [ -f "${REPORT_DIR}/unit-tests.json" ]; then
    UNIT_PASS=$(grep -c '"Action":"pass"' "${REPORT_DIR}/unit-tests.json" 2>/dev/null || echo 0)
    UNIT_FAIL=$(grep -c '"Action":"fail"' "${REPORT_DIR}/unit-tests.json" 2>/dev/null || echo 0)
    UNIT_SKIP=$(grep -c '"Action":"skip"' "${REPORT_DIR}/unit-tests.json" 2>/dev/null || echo 0)
fi

# Parse system test results
if [ -f "${REPORT_DIR}/system-tests.json" ]; then
    SYSTEM_PASS=$(grep -c '"Action":"pass"' "${REPORT_DIR}/system-tests.json" 2>/dev/null || echo 0)
    SYSTEM_FAIL=$(grep -c '"Action":"fail"' "${REPORT_DIR}/system-tests.json" 2>/dev/null || echo 0)
    SYSTEM_SKIP=$(grep -c '"Action":"skip"' "${REPORT_DIR}/system-tests.json" 2>/dev/null || echo 0)
fi

TOTAL_PASS=$((UNIT_PASS + SYSTEM_PASS))
TOTAL_FAIL=$((UNIT_FAIL + SYSTEM_FAIL))
TOTAL_SKIP=$((UNIT_SKIP + SYSTEM_SKIP))
TOTAL=$((TOTAL_PASS + TOTAL_FAIL + TOTAL_SKIP))

# Determine overall status
if [ "$TOTAL_FAIL" -gt 0 ]; then
    STATUS="❌ FAILED"
    STATUS_BADGE="failing"
elif [ "$TOTAL_PASS" -gt 0 ]; then
    STATUS="✅ PASSED"
    STATUS_BADGE="passing"
else
    STATUS="⚠️ NO TESTS"
    STATUS_BADGE="unknown"
fi

# Generate timestamp
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GENERATED_AT=$(date +"%Y-%m-%d %H:%M:%S %Z")

# Generate Markdown report
cat > "${OUTPUT_FILE}" <<EOF
# OpenTrusty Test Report

**Generated:** ${GENERATED_AT}  
**Status:** ${STATUS}

---

## Summary

| Category | Pass | Fail | Skip | Total |
|----------|------|------|------|-------|
| Unit Tests | ${UNIT_PASS} | ${UNIT_FAIL} | ${UNIT_SKIP} | $((UNIT_PASS + UNIT_FAIL + UNIT_SKIP)) |
| System Tests | ${SYSTEM_PASS} | ${SYSTEM_FAIL} | ${SYSTEM_SKIP} | $((SYSTEM_PASS + SYSTEM_FAIL + SYSTEM_SKIP)) |
| **Total** | **${TOTAL_PASS}** | **${TOTAL_FAIL}** | **${TOTAL_SKIP}** | **${TOTAL}** |

---

## Test Categories

### Unit Tests (UT)

Unit tests validate individual components with mocked dependencies.

- **AuthZ Tests**: Permission checking, scope isolation
- **OAuth2 Tests**: Code exchange, PKCE, token lifecycle
- **OIDC Tests**: Claim generation, sub stability, at_hash
- **Tenant Tests**: Role validation, isolation logic

### System Tests (ST)

System/integration tests validate end-to-end flows with real PostgreSQL.

- **Tenant Isolation**: Cross-tenant access prevention
- **Authorization**: Permission enforcement
- **OAuth2 Flows**: Token exchange, refresh, revocation
- **OIDC Compliance**: ID token issuance rules

---

## Test Execution

\`\`\`bash
# Run unit tests
make test-unit

# Run system tests (requires Docker PostgreSQL)
make test-system

# Generate test reports
make test-report-all
\`\`\`

---

*Report generated by OpenTrusty CI/CD Pipeline*
EOF

# Generate JSON summary for docs integration
cat > "${SUMMARY_FILE}" <<EOF
{
  "timestamp": "${TIMESTAMP}",
  "status": "${STATUS_BADGE}",
  "summary": {
    "total": ${TOTAL},
    "pass": ${TOTAL_PASS},
    "fail": ${TOTAL_FAIL},
    "skip": ${TOTAL_SKIP}
  },
  "unit_tests": {
    "pass": ${UNIT_PASS},
    "fail": ${UNIT_FAIL},
    "skip": ${UNIT_SKIP}
  },
  "system_tests": {
    "pass": ${SYSTEM_PASS},
    "fail": ${SYSTEM_FAIL},
    "skip": ${SYSTEM_SKIP}
  }
}
EOF

echo "✅ Test report generated:"
echo "   - Markdown: ${OUTPUT_FILE}"
echo "   - JSON: ${SUMMARY_FILE}"
echo ""
echo "📈 Results: ${TOTAL_PASS} passed, ${TOTAL_FAIL} failed, ${TOTAL_SKIP} skipped"
